baseURL = "/"
languageCode = "en-us"
title = "Google Cloud SDK Javadocs"

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"

[[module.imports]]
path = "github.com/google/docsy/dependencies"
contentDir = "content/"
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "tango"
enableInlineShortcodes = true

[params]
libraries_bom_version = "v26.17.0"

[params.ui]
sidebar_menu = true
ul_show = 1
sidebar_menu_foldable = true
sidebar_cache_limit = 1000
sidebar_search_disable = true
