name: Generate Javadocs for handwritten libraries
# Run this workflow once the site/data/variables.yaml file has been updated
on:
  push:
    paths:
    - 'site/data/**'
  pull_request:
    paths:
    - 'site/data/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: maven

    - name: Generate javadocs for each handwritten library
      run: |
        while read -r repo directory tag artifact
        do
          echo "REPO=$repo"
          echo "DIRECTORY=$directory"
          echo "TAG=$tag"
          echo "Creating and clearing directory for javadocs for ${artifact}"
          mkdir -p site/static/${artifact} # Make sure the output directory exists
          rm -rf site/static/${artifact}/ # Clear any existing files in the output directory
          echo "Cloning into ${repo}"
          git clone https://github.com/${repo}.git
          git -C "${directory}" checkout $tag
          echo "Generating javadocs for ${artifact}"
          mvn -f ${directory}/pom.xml javadoc:aggregate -Dmaven.javadoc.failOnError=false && mv ${directory}/target/site/apidocs/ site/static/${artifact}/
        done < .github/workflows/javadocs_scripts/handwritten_libraries_javadocs_modules.txt

    - name: Commit Javadocs
      run: |
        git -C site/static/ add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add Javadocs for handwritten library modules" -a || echo "No changes to commit"
        git pull --rebase origin main
        git push
      env:
        GH_TOKEN: ${{ github.token }}